[package]
name = "fuse"
version = "0.1.0"
authors = ["Christian Th√§ter <ct@pipapo.org>"]
edition = "2018"


[dependencies]
clap = "2.33"
log = "0.4"
libc = "0.2"
thiserror = "1.0"
fuser = "0.7"
objectstore = { path = "../objectstore" }
parking_lot = "0.11"
