[package]
name = "fuse"
version = "0.1.0"
authors = ["Christian Th√§ter <ct@pipapo.org>"]
edition = "2018"


[dependencies]
fuser = "0.9"
objectstore = { path = "../objectstore" }
uberall = { path = "../uberall" }
